---
title: "Data Science for Public Policy"
subtitle: "Assignment 04"
author: "Minji Kang - mk2322, Ziqiao Shan - zs352"
execute:
  warning: false
format:
  html:
    embed-resources: true
---

```{r}
# if the program hasn't downloaded the "wbstats" package, run "install.packages("wbstats")".
library(tidyverse)
library(ggplot2)
# we found the package called wbstats~~~~~ need to put explains
library(wbstats)
japanbirthrate <- wb_data(country = "Japan", indicator = c("SP.DYN.CBRT.IN"))
japanwolaborforce <- wb_data(country = "Japan", indicator = c("SL.TLF.TOTL.FE.ZS"))
japandataset <- full_join(japanbirthrate, japanwolaborforce)
newdata <- japandataset |>
  filter(date >= 1990, date <= 2022)
```

1) wbstats meaning (need to revise it later)
https://cran.r-project.org/web/packages/wbstats/wbstats.pdf

2) We got our dataset from World Bank
Source of the data:
https://data.worldbank.org/indicator/SP.DYN.TFRT.IN?locations=JP

# 1st ggplot2 Graph (Bar Chart)

```{r}
# First ggplot2 Graph (Bar Chart)
# **Need to add a proper subtitle
# **Need to design it later (font size color etc)

# try 1 (got a warning sign)
ggplot(newdata, mapping = aes(x = SL.TLF.TOTL.FE.ZS, y = SP.DYN.CBRT.IN, fill = date)) +
  geom_col(width = 0.03) +
  labs(title = "Annual Changes in Birth Rate and Female Labor Force by 1990-2022",
       subtitle = ".",
       x = "Female Labor Force",
       y = "Birth Rate",
       caption = "Data Source: World Bank Group")

# new version
ggplot(newdata, mapping = aes(x = SP.DYN.CBRT.IN, y = SL.TLF.TOTL.FE.ZS, fill = date)) +
  geom_col(width = 0.03) +
  labs(title = "Annual Changes in Birth Rate and Female Labor Force by 1990-2022",
       subtitle = ".",
       x = "Birth Rate",
       y = "Female Labor Force",
       caption = "Data Source: World Bank Group")
```

# 2nd ggplot2 Graph (Scatterplot)

```{r}
# Second ggplot2 Graph (Scatterplot)
# **Need to add a proper subtitle
# **Need to design it later (font size color etc)
# **Need to add more aes in aes

# try 1
ggplot(newdata, mapping = aes(x = SP.DYN.CBRT.IN, y = SL.TLF.TOTL.FE.ZS)) +
  geom_point(alpha = 0.3, color = "green") +
  geom_smooth(method = "lm", color = "pink") +
  labs(title = "Annual Changes in Birth Rate and Female Labor Force by 1990-2022",
       subtitle = ".",
       x = "Birth Rate",
       y = "Female Labor Force",
       caption = "Data Source: World Bank Group") +
  theme_minimal()
```

# 3rd ggplot2 Graph (Histogram)

```{r}

```

# 4th ggplot2 Graph (Line Plot)

```{r}

```
